import type { Metadata } from "next";
import { Bai_Jamjuree } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, unstable_setRequestLocale } from "next-intl/server";
import { DeviceProvider } from "../context/DeviceContext";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import QueryProvider from "../../lib/QueryProvider";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { AuthProvider } from "../context/AuthContext";

const inter = Bai_Jamjuree({ subsets: ["latin"], weight: ["400", "600", "700", "200", "300", "500"] });
const locales = ["en", "ar"];

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();
  unstable_setRequestLocale(locale);

  return (
    <html lang={locale}>
      <body style={{ textAlign: locale === "ar" ? "right" : "left" }} className={`${inter.className}`}>
        <QueryProvider>
          <DeviceProvider>
            <AuthProvider>
              <ToastContainer
                position="top-center"
                autoClose={3500}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                pauseOnFocusLoss
                pauseOnHover={false}
                theme="light"
              />

              <ReactQueryDevtools initialIsOpen={false} />

              <NextIntlClientProvider messages={messages}>{children}</NextIntlClientProvider>
            </AuthProvider>
          </DeviceProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
