// Documents
import {
  blogTag,
  blogPost,
  betweenTheBracketPost,
  blogHomepage,
  blogTopic,
  betweenTheBracketsHomepage,
  devBlogHomepage,
  capabilitiesPage,
  checklist,
  clientStory,
  company,
  cta,
  ebook,
  event,
  footer,
  glossaryTerm,
  guide,
  header,
  hubspotForm,
  industry,
  industryPage,
  legalPage,
  listingPage,
  meetingThankYouPage,
  page,
  paidLandingPage,
  person,
  podcast,
  publication,
  redirects,
  report,
  review,
  sharedComponent,
  sharedModule,
  solution,
  solutionsPage,
  stage,
  stagePage,
  technology,
  technologyPage,
  testimonial,
  token,
  useCase,
  useCasePage,
  video,
  webstacksDevPost,
} from '../schemas/documents'
// Objects
import { socialLink } from './objects'
import {
  blogRichText,
  colorablePlainText,
  complexRichText,
  legalRichText,
  minimalRichText,
  simpleRichText,
  simpleRichTextWithImages,
} from '../schemas/fields'
import { codeSnippet } from '../schemas/fields/codeSnippet'

export const schemas = [
  blogPost,
  betweenTheBracketPost,
  webstacksDevPost,
  betweenTheBracketsHomepage,
  devBlogHomepage,
  clientStory,
  company,
  cta,
  event,
  footer,
  glossaryTerm,
  header,
  guide,
  industry,
  industryPage,
  legalPage,
  hubspotForm,
  socialLink,

  page,
  paidLandingPage,
  listingPage,
  meetingThankYouPage,
  person,
  publication,
  report,
  sharedComponent,
  sharedModule,

  testimonial,
  token,
  blogTag,
  blogTopic,
  blogHomepage,
  solution,
  stage,
  technology,
  useCase,
  useCasePage,
  video,
  ebook,
  checklist,
  capabilitiesPage,
  solutionsPage,
  stagePage,
  technologyPage,
  podcast,
  review,

  blogRichText,
  colorablePlainText,
  complexRichText,
  legalRichText,
  minimalRichText,
  simpleRichText,
  simpleRichTextWithImages,
  codeSnippet,
  redirects,
]
